<?php

use yii\db\Migration;

/**
 * Class m180414_151147_jobs_cate
 */
class m180414_151147_jobs_cate extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $this->execute("ALTER TABLE `tn_job_categories` CHANGE `name` `name` VARCHAR(255) CHARSET utf8 COLLATE utf8_general_ci NULL; ");
        $this->execute("TRUNCATE TABLE `tn_job_categories`;");
        $this->execute("INSERT  INTO `tn_job_categories`(`id`,`parent_id`,`name`,`description`,`icon_class`,`image`,`created_at`,`updated_at`,`created_by`,`updated_by`,`arranged`,`total_jobs`,`total_cv`,`status`) 
		VALUES
		 (6,0,'XÂY DỰNG',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (7,6,'Kiến trúc/Thiết kế nội thất',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (8,6,'Bất động sản',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (9,0,'TRUYỀN THÔNG',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (10,9,'Viễn Thông ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (11,9,'Truyền hình/Truyền thông/Báo chí',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (12,9,'Mỹ Thuật/Nghệ Thuật/Thiết Kế',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (13,9,'Quảng cáo/Khuyến mãi/Đối ngoại',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (14,9,'Internet/Online Media',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (15,9,'In ấn/Xuất bản',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (16,0,'DỊCH VỤ TÀI CHÍNH',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (17,16,'Ngân hàng',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (18,16,'Kiểm toán',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (19,16,'Tài chính/Đầu tư',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (20,16,'Chứng khoán',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (21,16,'Bảo hiểm',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (22,0,'HÀNG TIÊU DÙNG & BÁN LẺ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (23,22,'Hàng tiêu dùng',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (24,22,'Hàng gia dụng',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (25,22,'Bán lẻ/Bán sỉ ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (26,22,'Thực phẩm & Đồ uống',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (27,22,'Thời trang ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (28,22,'Hàng cao cấp',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (29,0,'KHÁCH SẠN & DU LỊCH',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (30,0,'Hàng không/Du lịch',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (31,30,'Nhà hàng/Khách sạn',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (32,0,'KỸ THUẬT',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (33,32,'Điện/Điện tử',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (34,32,'Cơ khí',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (35,32,'Hóa học/Hóa sinh',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (36,32,'Môi trường/Xử lý chất thải',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (37,32,'Điện lạnh/Nhiệt lạnh',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (38,0,'SẢN XUẤT',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (39,38,'Dầu khí',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (40,38,'Dệt may/Giày da',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (41,38,'Dược Phẩm/Công nghệ sinh học',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (42,38,'Ôtô/Tự động hóa',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (43,38,'Nông/Lâm nghiệp',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (44,38,'Sản phẩm công nghiệp',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (45,38,'Công nghệ cao',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (46,38,'Địa chất/Khoáng sản',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (47,0,'Y TẾ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (48,47,'Y tế/Chăm sóc sức khỏe',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (49,47,'Bác sĩ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (50,47,'Y sĩ/Hộ lý ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (51,47,'Dược sĩ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (52,47,'Trình dược viên',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (53,0,'DỊCH VỤ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (54,53,'Phi chính phủ/Phi lợi nhuận',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (55,53,'Giáo dục/Đào tạo',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (56,53,'Y tế/Chăm sóc sức khỏe',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (57,53,'Tư vấn',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (58,0,'VẬN TẢI',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (59,58,'Vận chuyển/Giao nhận',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (60,58,'Kho vận',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (61,58,'Hàng hải',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (62,0,'GIAO DỊCH KHÁCH HÀNG',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (63,62,'Marketing',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (64,62,'Bán hàng',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (65,62,'Dịch vụ khách hàng',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (66,62,'Bán hàng kỹ thuật',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (67,0,'BỘ PHẬN HỖ TRỢ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (68,67,'Hành chánh/Thư ký',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (69,67,'Kế toán',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (70,67,'Nhân sự',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (71,67,'Biên/phiên dịch',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (72,67,'Pháp lý',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (73,0,'KỸ THUẬT - CÔNG NGHỆ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (74,73,'IT - Phần cứng/Mạng',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (75,73,'IT - Phần mềm',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (76,0,'HỖ TRỢ SẢN XUẤT',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (77,76,'Xuất nhập khẩu',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (78,0,'QA/QC',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (79,78,'Sản Xuất',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (80,78,'Thu Mua/Vật Tư/Cung Vận',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (81,78,'An toàn lao động',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (82,78,'Bảo trì/Sửa chữa',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL),
		 (83,78,'Hoạch định/Dự án',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL);");
        $this->execute("UPDATE `tn_job_categories` SET `status` = 1;");
        $this->execute("ALTER TABLE `tn_candidate` ADD COLUMN `client_status` TINYINT(1) DEFAULT 1 NULL AFTER `star`;");
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        echo "m180414_151147_jobs_cate cannot be reverted.\n";

        return false;
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m180414_151147_jobs_cate cannot be reverted.\n";

        return false;
    }
    */
}
